name: Build Images

on:
  push:
    branches: master

jobs:
  php:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [7.2, 7.3, 7.4, 8.0]
        
        
    name: 'Docker PHP Release ${{ matrix.version }}'

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Information
        run: echo "Building Images for PHP ${{ matrix.version }}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Docker/Images/PHP/Dockerfile
          tags: |
            arlonwip/php:${{ matrix.version }}
          build-args: |
            VERSION=${{ matrix.version }}

  mysql:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [5.7, 8]
        
        
    name: 'Docker MySQL Release ${{ matrix.version }}'

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Information
        run: echo "Building Images for MySQL ${{ matrix.version }}"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Docker/Images/MySQL/Dockerfile
          tags: arlonwip/mysql:${{ matrix.version }}
          build-args: |
            VERSION=${{ matrix.version }}
