name: Build Images

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [7.2, 7.3, 7.4, 8.0]
        
        
    name: 'Docker PHP Release ${{ matrix.version }}'

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Docker/Images/PHP/Dockerfile
          tags: arlonwip/php:${{ matrix.version }}
          build-args: |
            version=${{ matrix.version }}
